version: "3.9"
services:
  api:
    build: .
    container_name: sgm-api
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    volumes:
      # persist SQLite DB between runs
      - sgm_data:/data
    restart: unless-stopped
    # Uncomment the next two lines to auto-seed on every start
    # environment:
    #   SEED: "1"

volumes:
  sgm_data:
    # named volume managed by Docker
