"""init schema

Revision ID: d97844729f71
Revises: 
Create Date: 2025-10-31 15:10:57.953329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd97844729f71'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('meeting_weekday', sa.Integer(), nullable=True))
    op.add_column('groups', sa.Column('meeting_start_min', sa.Integer(), nullable=True))
    op.add_column('groups', sa.Column('meeting_end_min', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'meeting_end_min')
    op.drop_column('groups', 'meeting_start_min')
    op.drop_column('groups', 'meeting_weekday')
    # ### end Alembic commands ###
